Socket {
    _events: [Object: null prototype] {
      userlogin: [AsyncFunction (anonymous)],
      check_socket: [AsyncFunction (anonymous)],
      request_call: [AsyncFunction (anonymous)],
      joincall: [AsyncFunction (anonymous)],
      get_user_in_room: [AsyncFunction (anonymous)],
      get_remoteclient_bypeerid: [AsyncFunction (anonymous)],
      disconnect: [AsyncFunction (anonymous)]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    nsp: <ref *1> Namespace {
      _events: [Object: null prototype] {
        connection: [AsyncFunction (anonymous)]
      },
      _eventsCount: 1,
      _maxListeners: undefined,
      sockets: Map(3) {
        'B75Afq23-7x9bD_RAAAC' => [Socket],
        'wxS22olI1IHCay3CAAAD' => [Socket],
        'PzB263-bywN38NvqAAAF' => [Socket]
      },
      _fns: [],
      _ids: 0,
      server: Server {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _nsps: [Map],
        parentNsps: Map(0) {},
        _path: '/socket.io',
        clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
        _connectTimeout: 45000,
        _serveClient: true,
        _parser: [Object],
        encoder: Encoder {},
        _adapter: [class Adapter extends EventEmitter],
        sockets: [Circular *1],
        opts: [Object],
        eio: [Server],
        httpServer: [Server],
        engine: [Server],
        [Symbol(kCapture)]: false
      },
      name: '/',
      adapter: Adapter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        nsp: [Circular *1],
        rooms: [Map],
        sids: [Map],
        encoder: Encoder {},
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false
    },
    client: Client {
      sockets: Map(0) {},
      nsps: Map(0) {},
      server: Server {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _nsps: [Map],
        parentNsps: Map(0) {},
        _path: '/socket.io',
        clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
        _connectTimeout: 45000,
        _serveClient: true,
        _parser: [Object],
        encoder: Encoder {},
        _adapter: [class Adapter extends EventEmitter],
        sockets: [Namespace],
        opts: [Object],
        eio: [Server],
        httpServer: [Server],
        engine: [Server],
        [Symbol(kCapture)]: false
      },
      conn: Socket {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        id: 'U3_AoJy0d0kEKtFDAAAG',
        server: [Server],
        upgrading: false,
        upgraded: true,
        _readyState: 'closed',
        writeBuffer: [],
        packetsFn: [],
        sentCallbackFn: [],
        cleanupFn: [],
        request: [IncomingMessage],
        protocol: 4,
        remoteAddress: '::1',
        checkIntervalTimer: null,
        upgradeTimeoutTimer: null,
        pingTimeoutTimer: Timeout {
          _idleTimeout: -1,
          _idlePrev: null,
          _idleNext: null,
          _idleStart: 22783,
          _onTimeout: null,
          _timerArgs: undefined,
          _repeat: null,
          _destroyed: true,
          [Symbol(refed)]: true,
          [Symbol(kHasPrimitive)]: false,
          [Symbol(asyncId)]: 704,
          [Symbol(triggerId)]: 703
        },
        pingIntervalTimer: Timeout {
          _idleTimeout: -1,
          _idlePrev: null,
          _idleNext: null,
          _idleStart: 21152,
          _onTimeout: null,
          _timerArgs: undefined,
          _repeat: null,
          _destroyed: true,
          [Symbol(refed)]: true,
          [Symbol(kHasPrimitive)]: false,
          [Symbol(asyncId)]: 634,
          [Symbol(triggerId)]: 0
        },
        transport: [WebSocket],
        [Symbol(kCapture)]: false
      },
      encoder: Encoder {},
      decoder: Decoder { _callbacks: {} },
      id: 'U3_AoJy0d0kEKtFDAAAG',
      onclose: [Function: bound onclose],
      ondata: [Function: bound ondata],
      onerror: [Function: bound onerror],
      ondecoded: [Function: bound ondecoded],
      connectTimeout: undefined
    },
    data: {},
    connected: false,
    acks: Map(0) {},
    fns: [],
    flags: {},
    server: <ref *2> Server {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _nsps: Map(1) { '/' => [Namespace] },
      parentNsps: Map(0) {},
      _path: '/socket.io',
      clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
      _connectTimeout: 45000,
      _serveClient: true,
      _parser: {
        protocol: 5,
        PacketType: [Object],
        Encoder: [class Encoder],
        Decoder: [class Decoder extends Emitter]
      },
      encoder: Encoder {},
      _adapter: [class Adapter extends EventEmitter],
      sockets: <ref *1> Namespace {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        sockets: [Map],
        _fns: [],
        _ids: 0,
        server: [Circular *2],
        name: '/',
        adapter: [Adapter],
        [Symbol(kCapture)]: false
      },
      opts: { cors: [Object] },
      eio: Server {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        clients: [Object],
        clientsCount: 3,
        opts: [Object],
        corsMiddleware: [Function: corsMiddleware],
        ws: [WebSocketServer],
        [Symbol(kCapture)]: false
      },
      httpServer: Server {
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        _events: [Object: null prototype],
        _eventsCount: 5,
        _maxListeners: undefined,
        _connections: 2,
        _handle: [TCP],
        _usingWorkers: false,
        _workers: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        noDelay: false,
        keepAlive: false,
        keepAliveInitialDelay: 0,
        httpAllowHalfOpen: false,
        timeout: 0,
        keepAliveTimeout: 5000,
        maxHeadersCount: null,
        maxRequestsPerSocket: 0,
        headersTimeout: 60000,
        requestTimeout: 0,
        _connectionKey: '6::::3000',
        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
        [Symbol(ServerResponse)]: [Function: ServerResponse],
        [Symbol(kCapture)]: false,
        [Symbol(async_id_symbol)]: 10
      },
      engine: Server {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        clients: [Object],
        clientsCount: 3,
        opts: [Object],
        corsMiddleware: [Function: corsMiddleware],
        ws: [WebSocketServer],
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false
    },
    adapter: <ref *3> Adapter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      nsp: <ref *1> Namespace {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        sockets: [Map],
        _fns: [],
        _ids: 0,
        server: [Server],
        name: '/',
        adapter: [Circular *3],
        [Symbol(kCapture)]: false
      },
      rooms: Map(5) {
        'B75Afq23-7x9bD_RAAAC' => [Set],
        'wxS22olI1IHCay3CAAAD' => [Set],
        'PzB263-bywN38NvqAAAF' => [Set],
        'private_room_1' => [Set],
        '1' => [Set]
      },
      sids: Map(3) {
        'B75Afq23-7x9bD_RAAAC' => [Set],
        'wxS22olI1IHCay3CAAAD' => [Set],
        'PzB263-bywN38NvqAAAF' => [Set]
      },
      encoder: Encoder {},
      [Symbol(kCapture)]: false
    },
    id: '8ifA4-IOBSIKr3SOAAAH',
    handshake: {
      headers: {
        host: 'e22f-116-109-211-235.ngrok.io',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.62 Safari/537.36',
        accept: '*/*',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.9,vi;q=0.8,nl;q=0.7',
        cookie: 'user=j%3A%7B%22id%22%3A1%2C%22username%22%3A%22usm1%22%2C%22fullname%22%3A%22Nguy%E1%BB%85n%20V%C4%83n%20A%22%7D; peerID=a9ca6f2e-f21c-4e8f-8b2d-a12e8713370e; connect.sid=s%3ArNx-WPUcBo9hdp35VT9YaCpbK1NLFvUH.0augyVZESEusw0CkiY2jmQK3ax3veiHscsk0RHKsS6o',
        referer: 'https://e22f-116-109-211-235.ngrok.io/home',
        'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'x-forwarded-for': '2402:800:63b7:fcc6:4887:fbc1:dfd3:62b4',
        'x-forwarded-proto': 'https'
      },
      time: 'Sun May 29 2022 16:13:17 GMT+0700 (Giờ Đông Dương)',
      address: '::1',
      xdomain: false,
      secure: false,
      issued: 1653815597713,
      url: '/socket.io/?EIO=4&transport=polling&t=O4F5rTu',
      query: [Object: null prototype] {
        EIO: '4',
        transport: 'polling',
        t: 'O4F5rTu'
      },
      auth: {}
    },
    [Symbol(kCapture)]: false
  }
  ================== DISCONNECT ===================
  Ngắt kết nối: B75Afq23-7x9bD_RAAAC
  ================== USER DISCONNECT ROOMS===================
  Socket {
    _events: [Object: null prototype] {
      userlogin: [AsyncFunction (anonymous)],
      check_socket: [AsyncFunction (anonymous)],
      request_call: [AsyncFunction (anonymous)],
      joincall: [AsyncFunction (anonymous)],
      get_user_in_room: [AsyncFunction (anonymous)],
      get_remoteclient_bypeerid: [AsyncFunction (anonymous)],
      disconnect: [AsyncFunction (anonymous)]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    nsp: <ref *1> Namespace {
      _events: [Object: null prototype] {
        connection: [AsyncFunction (anonymous)]
      },
      _eventsCount: 1,
      _maxListeners: undefined,
      sockets: Map(2) {
        'wxS22olI1IHCay3CAAAD' => [Socket],
        'PzB263-bywN38NvqAAAF' => [Socket]
      },
      _fns: [],
      _ids: 0,
      server: Server {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _nsps: [Map],
        parentNsps: Map(0) {},
        _path: '/socket.io',
        clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
        _connectTimeout: 45000,
        _serveClient: true,
        _parser: [Object],
        encoder: Encoder {},
        _adapter: [class Adapter extends EventEmitter],
        sockets: [Circular *1],
        opts: [Object],
        eio: [Server],
        httpServer: [Server],
        engine: [Server],
        [Symbol(kCapture)]: false
      },
      name: '/',
      adapter: Adapter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        nsp: [Circular *1],
        rooms: [Map],
        sids: [Map],
        encoder: Encoder {},
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false
    },
    client: Client {
      sockets: Map(0) {},
      nsps: Map(0) {},
      server: Server {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _nsps: [Map],
        parentNsps: Map(0) {},
        _path: '/socket.io',
        clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
        _connectTimeout: 45000,
        _serveClient: true,
        _parser: [Object],
        encoder: Encoder {},
        _adapter: [class Adapter extends EventEmitter],
        sockets: [Namespace],
        opts: [Object],
        eio: [Server],
        httpServer: [Server],
        engine: [Server],
        [Symbol(kCapture)]: false
      },
      conn: Socket {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        id: 'cxRnsjNgorzke5nRAAAA',
        server: [Server],
        upgrading: false,
        upgraded: false,
        _readyState: 'closed',
        writeBuffer: [Array],
        packetsFn: [],
        sentCallbackFn: [],
        cleanupFn: [],
        request: [IncomingMessage],
        protocol: 4,
        remoteAddress: '::ffff:127.0.0.1',
        checkIntervalTimer: null,
        upgradeTimeoutTimer: null,
        pingTimeoutTimer: Timeout {
          _idleTimeout: -1,
          _idlePrev: null,
          _idleNext: null,
          _idleStart: 26734,
          _onTimeout: null,
          _timerArgs: undefined,
          _repeat: null,
          _destroyed: true,
          [Symbol(refed)]: true,
          [Symbol(kHasPrimitive)]: false,
          [Symbol(asyncId)]: 722,
          [Symbol(triggerId)]: 56
        },
        pingIntervalTimer: Timeout {
          _idleTimeout: 25000,
          _idlePrev: null,
          _idleNext: null,
          _idleStart: 1732,
          _onTimeout: null,
          _timerArgs: undefined,
          _repeat: null,
          _destroyed: true,
          [Symbol(refed)]: true,
          [Symbol(kHasPrimitive)]: false,
          [Symbol(asyncId)]: 56,
          [Symbol(triggerId)]: 0
        },
        transport: [Polling],
        [Symbol(kCapture)]: false
      },
      encoder: Encoder {},
      decoder: Decoder { _callbacks: {} },
      id: 'cxRnsjNgorzke5nRAAAA',
      onclose: [Function: bound onclose],
      ondata: [Function: bound ondata],
      onerror: [Function: bound onerror],
      ondecoded: [Function: bound ondecoded],
      connectTimeout: undefined
    },
    data: {},
    connected: false,
    acks: Map(0) {},
    fns: [],
    flags: {},
    server: <ref *2> Server {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _nsps: Map(1) { '/' => [Namespace] },
      parentNsps: Map(0) {},
      _path: '/socket.io',
      clientPathRegex: /^\/socket\.io\/socket\.io(\.msgpack|\.esm)?(\.min)?\.js(\.map)?(?:\?|$)/,
      _connectTimeout: 45000,
      _serveClient: true,
      _parser: {
        protocol: 5,
        PacketType: [Object],
        Encoder: [class Encoder],
        Decoder: [class Decoder extends Emitter]
      },
      encoder: Encoder {},
      _adapter: [class Adapter extends EventEmitter],
      sockets: <ref *1> Namespace {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        sockets: [Map],
        _fns: [],
        _ids: 0,
        server: [Circular *2],
        name: '/',
        adapter: [Adapter],
        [Symbol(kCapture)]: false
      },
      opts: { cors: [Object] },
      eio: Server {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        clients: [Object],
        clientsCount: 2,
        opts: [Object],
        corsMiddleware: [Function: corsMiddleware],
        ws: [WebSocketServer],
        [Symbol(kCapture)]: false
      },
      httpServer: Server {
        maxHeaderSize: undefined,
        insecureHTTPParser: undefined,
        _events: [Object: null prototype],
        _eventsCount: 5,
        _maxListeners: undefined,
        _connections: 2,
        _handle: [TCP],
        _usingWorkers: false,
        _workers: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        noDelay: false,
        keepAlive: false,
        keepAliveInitialDelay: 0,
        httpAllowHalfOpen: false,
        timeout: 0,
        keepAliveTimeout: 5000,
        maxHeadersCount: null,
        maxRequestsPerSocket: 0,
        headersTimeout: 60000,
        requestTimeout: 0,
        _connectionKey: '6::::3000',
        [Symbol(IncomingMessage)]: [Function: IncomingMessage],
        [Symbol(ServerResponse)]: [Function: ServerResponse],
        [Symbol(kCapture)]: false,
        [Symbol(async_id_symbol)]: 10
      },
      engine: Server {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        clients: [Object],
        clientsCount: 2,
        opts: [Object],
        corsMiddleware: [Function: corsMiddleware],
        ws: [WebSocketServer],
        [Symbol(kCapture)]: false
      },
      [Symbol(kCapture)]: false
    },
    adapter: <ref *3> Adapter {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      nsp: <ref *1> Namespace {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        sockets: [Map],
        _fns: [],
        _ids: 0,
        server: [Server],
        name: '/',
        adapter: [Circular *3],
        [Symbol(kCapture)]: false
      },
      rooms: Map(4) {
        'wxS22olI1IHCay3CAAAD' => [Set],
        'PzB263-bywN38NvqAAAF' => [Set],
        'private_room_1' => [Set],
        '1' => [Set]
      },
      sids: Map(2) {
        'wxS22olI1IHCay3CAAAD' => [Set],
        'PzB263-bywN38NvqAAAF' => [Set]
      },
      encoder: Encoder {},
      [Symbol(kCapture)]: false
    },
    id: 'B75Afq23-7x9bD_RAAAC',
    handshake: {
      headers: {
        host: 'e22f-116-109-211-235.ngrok.io',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.62 Safari/537.36',
        accept: '*/*',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.9,vi;q=0.8,nl;q=0.7',
        cookie: 'user=j%3A%7B%22id%22%3A1%2C%22username%22%3A%22usm1%22%2C%22fullname%22%3A%22Nguy%E1%BB%85n%20V%C4%83n%20A%22%7D; peerID=a9ca6f2e-f21c-4e8f-8b2d-a12e8713370e; connect.sid=s%3AvAkdxsgEhekSEZ_WXfK8fRmBGl7ipFUL.U%2BQ6cs99xAv%2Bsqcpte151B0apGHGVM9sH6OmX9fUgIk',
        referer: 'https://e22f-116-109-211-235.ngrok.io/home',
        'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'x-forwarded-for': '2402:800:63b7:fcc6:4887:fbc1:dfd3:62b4',
        'x-forwarded-proto': 'https'
      },
      time: 'Sun May 29 2022 16:12:58 GMT+0700 (Giờ Đông Dương)',
      address: '::ffff:127.0.0.1',
      xdomain: false,
      secure: false,
      issued: 1653815578301,
      url: '/socket.io/?EIO=4&transport=polling&t=O4F5mkI',
      query: [Object: null prototype] {
        EIO: '4',
        transport: 'polling',
        t: 'O4F5mkI'
      },
      auth: {}
    },
    [Symbol(kCapture)]: false
  }